### ISSUE TITLE
Make (de)serialization method names consistent

### ISSUE THREAD

**Issue by copygirl** [copygirl/pomf#1]
Currently they're all over the place: `serialize`, `serializeTag`, `serializeToTag`

Branch: [patch-serialize](https://github.com/copygirl/pomf/tree/patch-serialize)
Pull request: FabricMC/pomf#71

**Comment by copygirl** [comment]
This is where `serialize` is currently being used.
I'm thinking of changing the marked entries.
- [ ] `public Block.serializeState(IBlockState state) => int`  
  `public Block.deserializeState(int) => IBlockState`
- [x] `protected BlockCrop.serializeState0(IBlockState) => int`  
  `public BlockCrop.deserializeState0(IBlockState) => IBlockState`  
  Needs fixing. Rename to `serializeCropAge` ?
- [x] `public TileEntity.serializeTag(TagCompound) => TagCompound`  
  `public TileEntity.deserializeTag(TagCompound) => void`
- [x] `private TileEntity.serializeTileData(TagCompound) => TagCompound`  
  Appears to be for default tile entity data: ID and position. `serializeIdentifyingTileData` ?
- [ ] `protected TileEntityWithLootTable.serializeLootTable(TagCompound) => boolean`  
  `protected TileEntityWithLootTable.deserializeLootTable(TagCompound) => boolean`
- [x] `public Entity.serializeToTag(TagCompound) => TagCompound`  
  `public Entity.deserializeFromTag(TagCompound) => void`  
  Should probably be either `serialize` or `serializeEntity` ?
- [x] `protected abstract Entity.serializeEntityTag(TagCompound) => void`  
  `protected abstract Entity.deserializeEntityTag(TagCompound) => void`  
  Doesn't clarify much. `serializeEntityData`, `serializeCustomEntityData` ?
- [ ] `public ServerConfigList.EntryDeSerializer.serialize`  
  `public ITextComponent.DeSerializer.serialize`  
  `public Style.DeSerializer.serialize`  
  `public JsonHelper.deserialize`  
  JSON related, but this might be a reason to consider switching to `Entity.serialize`.
- [x] `public ServerEntry.serializeTag() => TagCompound`  
  `public static ServerEntry.deserializeTag(TagCompound) => ServerEntry`  
  Different style than usual, but should probably be changed to `serialize` as well.
- [x] `public GameRules.serializeToTag() => TagCompound`  
  `public GameRules.deserializeFromTag(TagCompound) => void`  
  Same as above.

**edit:** Forgot about the following:
- [ ] `public ItemStack.serialize(TagCompound) => TagCompound`  
  Constructor deserializes: `public ItemStack(TagCompound)`
- [ ] `public static DataTracker.serializePacket(List<Entry>, PacketByteBuf) => void`  
  `public DataTracker.serializePacket(PacketByteBuf) => void`  
  `public static DataTracker.deserializePacket(PacketByteBuf) => List<Entry>`
- [x] `public PotionEffect.serializeTag(TagCompound) => TagCompound`  
  `public static PotionEffect.deserializeTag(TagCompound) => PotionEffect`
- [x] `public CommandBlockExecutor.serializeTag(TagCompound) => TagCompound`  
  `public CommandBlockExecutor.deserializeTag(TagCompound) => void`

**Comment by copygirl** [comment]
It might be worth considering if the method should be named depending on the way it's used. For example, `ServerEntry` sticks out with its static method, it could even be named `deserializeFromTag`. Though I think I'm going to stick to `de/serialize` for everything that handles itself.

It's late. Will work on this and do a PR tomorrow.

**Comment by maxpowa** [comment]
> protected BlockCrop.serializeState0(IBlockState) => int
> public BlockCrop.deserializeState0(IBlockState) => IBlockState
> Needs fixing. Rename to serializeCropAge ?

Maybe `serializeCropData` since you're going with `serializeEntityData` later.

**Comment by copygirl** [comment]
@maxpowa It specifically handles age - it's manually increased by 1 in `randomTick`.
